/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import controller.Controller;
import domain.User;
import forms.airplanes.FrmAirplane;
import forms.flights.FrmFlight;
import forms.flights.SearchFlightsPanel;
import forms.passengers.FrmPassenger;
import forms.passengers.SearchPassengersPanel;
import forms.reservations.FrmReservation;
import forms.reservations.SearchReservationsPanel;
import java.awt.CardLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import session.Session;

/**
 *
 * @author User
 */
public class ClientMainForm extends javax.swing.JFrame {
    private JDialog frmNewPassenger;
    /**
     * Creates new form ClientMainForm
     */
    public ClientMainForm() {
        
        initComponents();
        populateCurrentUser();
        Controller.getInstance().setClientMainForm(this);
      
    }
    
    public JPanel getPanel() {
        return visiblePanel;
    }

    public JDialog getFrmNewPassenger() {
        return frmNewPassenger;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelCurrentUser = new javax.swing.JPanel();
        lblCurrentUser = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        visiblePanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPassengers = new javax.swing.JMenu();
        menuItemNewPassenger = new javax.swing.JMenuItem();
        menuItemSearchPassengers = new javax.swing.JMenuItem();
        menuFlights = new javax.swing.JMenu();
        menuItemNewFlight = new javax.swing.JMenuItem();
        menuItemSearchFlights = new javax.swing.JMenuItem();
        menuReservations = new javax.swing.JMenu();
        menuItemNewReservation = new javax.swing.JMenuItem();
        menuItemSearchReservations = new javax.swing.JMenuItem();
        menuAirplanes = new javax.swing.JMenu();
        menuItemNewAirplane = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client main form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelCurrentUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));

        lblCurrentUser.setText("Current user:");

        javax.swing.GroupLayout panelCurrentUserLayout = new javax.swing.GroupLayout(panelCurrentUser);
        panelCurrentUser.setLayout(panelCurrentUserLayout);
        panelCurrentUserLayout.setHorizontalGroup(
            panelCurrentUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurrentUserLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblCurrentUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCurrentUserLayout.setVerticalGroup(
            panelCurrentUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurrentUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMain.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout visiblePanelLayout = new javax.swing.GroupLayout(visiblePanel);
        visiblePanel.setLayout(visiblePanelLayout);
        visiblePanelLayout.setHorizontalGroup(
            visiblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        visiblePanelLayout.setVerticalGroup(
            visiblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        panelMain.add(visiblePanel, "card2");

        menuPassengers.setText("Passengers");

        menuItemNewPassenger.setText("New passenger");
        menuItemNewPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewPassengerActionPerformed(evt);
            }
        });
        menuPassengers.add(menuItemNewPassenger);

        menuItemSearchPassengers.setText("Search passengers");
        menuItemSearchPassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchPassengersActionPerformed(evt);
            }
        });
        menuPassengers.add(menuItemSearchPassengers);

        jMenuBar1.add(menuPassengers);

        menuFlights.setText("Flights");

        menuItemNewFlight.setText("New flight");
        menuItemNewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewFlightActionPerformed(evt);
            }
        });
        menuFlights.add(menuItemNewFlight);

        menuItemSearchFlights.setText("Search flights");
        menuItemSearchFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchFlightsActionPerformed(evt);
            }
        });
        menuFlights.add(menuItemSearchFlights);

        jMenuBar1.add(menuFlights);

        menuReservations.setText("Reservations");

        menuItemNewReservation.setText("New reservation");
        menuItemNewReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewReservationActionPerformed(evt);
            }
        });
        menuReservations.add(menuItemNewReservation);

        menuItemSearchReservations.setText("Search reservations");
        menuItemSearchReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchReservationsActionPerformed(evt);
            }
        });
        menuReservations.add(menuItemSearchReservations);

        jMenuBar1.add(menuReservations);

        menuAirplanes.setText("Airplanes");

        menuItemNewAirplane.setText("New airplane");
        menuItemNewAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewAirplaneActionPerformed(evt);
            }
        });
        menuAirplanes.add(menuItemNewAirplane);

        jMenuBar1.add(menuAirplanes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCurrentUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSearchPassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchPassengersActionPerformed
        visiblePanel = new SearchPassengersPanel(this);
        setPanel(visiblePanel);
                
    }//GEN-LAST:event_menuItemSearchPassengersActionPerformed

    private void menuItemSearchReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchReservationsActionPerformed
        visiblePanel = new SearchReservationsPanel(this);
        setPanel(visiblePanel);
        
    }//GEN-LAST:event_menuItemSearchReservationsActionPerformed

    private void menuItemNewPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewPassengerActionPerformed
        frmNewPassenger = new FrmPassenger(this, true, FrmMode.NEW);
        frmNewPassenger.setVisible(true);
        
    }//GEN-LAST:event_menuItemNewPassengerActionPerformed

    private void menuItemNewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewFlightActionPerformed
        JDialog frmNewFlight = new FrmFlight(this, true, FrmMode.NEW);
        frmNewFlight.setVisible(true);
        
    }//GEN-LAST:event_menuItemNewFlightActionPerformed

    private void menuItemSearchFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchFlightsActionPerformed
        visiblePanel = new SearchFlightsPanel(this);
        setPanel(visiblePanel);
                

    }//GEN-LAST:event_menuItemSearchFlightsActionPerformed

    private void menuItemNewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewReservationActionPerformed
        JDialog frmNewReservation = new FrmReservation(this, true, FrmMode.NEW);
        frmNewReservation.setVisible(true);
        
    }//GEN-LAST:event_menuItemNewReservationActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String message = Controller.getInstance().end();
        JOptionPane.showMessageDialog(this, message, "Goodbye!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_formWindowClosing

    private void menuItemNewAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewAirplaneActionPerformed
        JDialog frmAirplane = new FrmAirplane(this, true, FrmMode.NEW);
        frmAirplane.setVisible(true);
    }//GEN-LAST:event_menuItemNewAirplaneActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCurrentUser;
    private javax.swing.JMenu menuAirplanes;
    private javax.swing.JMenu menuFlights;
    private javax.swing.JMenuItem menuItemNewAirplane;
    private javax.swing.JMenuItem menuItemNewFlight;
    private javax.swing.JMenuItem menuItemNewPassenger;
    private javax.swing.JMenuItem menuItemNewReservation;
    private javax.swing.JMenuItem menuItemSearchFlights;
    private javax.swing.JMenuItem menuItemSearchPassengers;
    private javax.swing.JMenuItem menuItemSearchReservations;
    private javax.swing.JMenu menuPassengers;
    private javax.swing.JMenu menuReservations;
    private javax.swing.JPanel panelCurrentUser;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel visiblePanel;
    // End of variables declaration//GEN-END:variables

    private void populateCurrentUser() {
        User currentUser = Session.getInstance().getCurrentUser();
        lblCurrentUser.setText("Current user: " + currentUser.getFirstName() + " " + currentUser.getLastName());
    }
    
    public void setPanel(JPanel panel) {
        panelMain.removeAll();
        panelMain.revalidate();

        panelMain.add(panel);
        panelMain.revalidate();
    }
}
