/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.passengers;

import controller.Controller;
import domain.Passenger;
import forms.ClientMainForm;
import forms.FrmMode;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import transfer.Response;
import validator.FormValidator;

/**
 *
 * @author User
 */
public class FrmPassenger extends javax.swing.JDialog {
    Border border;
    Passenger p;
    SearchPassengersPanel spp;
    ClientMainForm cmf = Controller.getInstance().getClientMainForm();
    
    /**
     * Creates new form FrmPassener
     */
    public FrmPassenger(java.awt.Frame parent, boolean modal, FrmMode mode) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        adjustForm(mode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPassenger = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtCollectedPoints = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassportNo = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Passport no:");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setText("First name:");

        jLabel3.setText("Last name:");

        jLabel4.setText("Collected points:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPassengerLayout = new javax.swing.GroupLayout(panelPassenger);
        panelPassenger.setLayout(panelPassengerLayout);
        panelPassengerLayout.setHorizontalGroup(
            panelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPassengerLayout.createSequentialGroup()
                .addGroup(panelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPassengerLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(panelPassengerLayout.createSequentialGroup()
                                .addGroup(panelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(19, 19, 19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(panelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCollectedPoints)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassportNo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPassengerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addGap(34, 34, 34))
        );
        panelPassengerLayout.setVerticalGroup(
            panelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPassengerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassportNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCollectedPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(panelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)
                    .addComponent(btnUpdate))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(panelPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(!validation())
            return;
        
        String passportNo = txtPassportNo.getText();
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        int collectedPoints = Integer.parseInt(txtCollectedPoints.getText());
        
        Passenger p = new Passenger(passportNo, firstName, lastName, collectedPoints);

        Response response = Controller.getInstance().savePassenger(p);

        if (response.isSuccessful()) {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Successful", JOptionPane.INFORMATION_MESSAGE);
            resetForm();
            cmf.setPanel(new SearchPassengersPanel(cmf));
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Unsuccessful", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(!validation())
            return;
        
        String passportNo = txtPassportNo.getText();
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        int collectedPoints = Integer.parseInt(txtCollectedPoints.getText());
        
        p.setFirstName(firstName);
        p.setLastName(lastName);
        p.setCollectedPoints(collectedPoints);
        Response res = Controller.getInstance().updatePassenger(p);

        if (res.isSuccessful()) {
            JOptionPane.showMessageDialog(this, res.getMessage(), "Successful", JOptionPane.INFORMATION_MESSAGE);
            resetForm();
           
            //spp.populatePassengersTable();
            //spp.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, res.getMessage(), "Unsuccessful", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelPassenger;
    private javax.swing.JTextField txtCollectedPoints;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassportNo;
    // End of variables declaration//GEN-END:variables
    
    
    private void resetForm() {
        txtPassportNo.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtCollectedPoints.setText("");
    }
    
    private void adjustForm(FrmMode mode) {
    
        switch (mode) {
            case NEW:
                String title = "Add passenger:";
                border = BorderFactory.createTitledBorder(title);
                panelPassenger.setBorder(border);
                btnUpdate.setVisible(false);
                btnSave.setVisible(true);
                btnCancel.setVisible(true);                
                break;
            case VIEW:
                title = "View passenger:";
                border = BorderFactory.createTitledBorder(title);
                panelPassenger.setBorder(border);                
                btnSave.setVisible(false);
                btnUpdate.setVisible(false);
                btnCancel.setVisible(true);
                txtPassportNo.setEnabled(false);
                txtFirstName.setEnabled(false);
                txtLastName.setEnabled(false);
                txtCollectedPoints.setEnabled(false);
                break;
            case EDIT:                
                title = "Edit member:";
                border = BorderFactory.createTitledBorder(title);
                panelPassenger.setBorder(border);
                btnSave.setVisible(false);
                btnUpdate.setVisible(true);
                btnCancel.setVisible(true);
                txtPassportNo.setEnabled(false);
                break;
            
        }
    }
        
    // for EDIT and VIEW mode
    void populateForm(Passenger p, SearchPassengersPanel spp, FrmMode mode) {
        adjustForm(mode);
        this.p = p;
        this.spp = spp;
        txtPassportNo.setText(p.getPassportNo());
        txtFirstName.setText(p.getFirstName());
        txtLastName.setText(p.getLastName());
        txtCollectedPoints.setText(p.getCollectedPoints()+"");
    }
    
    private boolean validation() {
        if (!FormValidator.getInstance().validateEmpty(txtPassportNo, txtFirstName, txtLastName, txtCollectedPoints)) {
            JOptionPane.showMessageDialog(panelPassenger, FormValidator.getInstance().getValidationMessage(), "Error",JOptionPane.ERROR_MESSAGE );
            return false;
        }
        
        String passportNo = txtPassportNo.getText();
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        int collectedPoints = 0;
        
        if(passportNo.length() != 8){
            JOptionPane.showMessageDialog(this, "Passport number must consist of 8 digits.");
            return false;
        }

        try {
            collectedPoints = Integer.parseInt(txtCollectedPoints.getText());
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Collected points have to be numeric value!");
            return false;
        }
         
        return true;
    }
}
